"""CLI interface for CLI-agent-installer v2.0.

Provides commands for:
- Project initialization (manifest creation)
- Installation and updates (with checklist system)
- Update checking (GitHub API)
- Version display
- Checklist management (list, run, resume)
"""

import click
import json
from pathlib import Path
from typing import Optional

from .core import (
    VersionManager,
    ManifestManager,
    SyncManager,
    ChecklistEngine,
    StructuredLogger,
    LogType,
    Task,
    Step,
)
from .core.manifest import Manifest


@click.group()
@click.version_option(version="2.0.0", prog_name="installer")
@click.option("--verbose", "-v", is_flag=True, help="Enable verbose output")
@click.option("--log-level", type=click.Choice(["DEBUG", "INFO", "WARNING", "ERROR"]), default="INFO", help="Log level")
@click.pass_context
def cli(ctx, verbose, log_level):
    """CLI-agent-installer — Generic installer/updater for Python projects.

    Provides unified installation, updates, and management across projects.
    """
    ctx.ensure_object(dict)
    ctx.obj["verbose"] = verbose
    ctx.obj["log_level"] = log_level


@cli.command()
@click.argument("project_dir", type=click.Path())
@click.option("--repo", required=True, help="GitHub repository (owner/repo)")
@click.option("--version", help="Initial version (default: reads from git tag)")
@click.pass_context
def init(ctx, project_dir, repo, version):
    """Initialize installer in a project.

    Creates install/manifest.json and install.sh thin wrapper.
    """
    project_path = Path(project_dir).resolve()

    click.echo(f"📦 Initializing installer for {project_path}")

    # Create manifest
    manifest_manager = ManifestManager(project_path)
    manifest = manifest_manager.generate_template(
        repo=repo,
        version=version or "0.1.0",
    )
    manifest_manager.save(manifest)

    click.echo(f"✓ Created install/manifest.json (v{manifest.version})")

    # Create install.sh thin wrapper
    install_sh = project_path / "install.sh"
    install_content = f"""#!/bin/bash
# install.sh — Thin wrapper for CLI-agent-installer
# Generated by CLI-agent-installer v2.0

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Check if installer is available
if command -v installer &>/dev/null; then
    installer run "$PROJECT_DIR" "$@"
else
    echo "⚠️  CLI-agent-installer not found. Installing..."
    curl -fsSL https://raw.githubusercontent.com/Ruben-Alvarez-Dev/CLI-agent-installer/main/install.sh | bash
    installer run "$PROJECT_DIR" "$@"
fi
"""
    install_sh.write_text(install_content)
    install_sh.chmod(0o755)

    click.echo(f"✓ Created install.sh")

    click.echo(f"\n✓ Installer initialized for {project_path}")
    click.echo(f"  Repo: {repo}")
    click.echo(f"  Version: {manifest.version}")
    click.echo(f"\nNext steps:")
    click.echo(f"  1. Review install/manifest.json")
    click.echo(f"  2. Customize payload/preserve patterns")
    click.echo(f"  3. Commit changes")
    click.echo(f"  4. Run: bash install.sh")


@cli.command()
@click.argument("project_dir", type=click.Path())
@click.option("--dry-run", is_flag=True, help="Don't make changes")
@click.option("--resume", help="Resume from checkpoint ID")
@click.option("--no-checklist", is_flag=True, help="Run without checklist system")
@click.pass_context
def run(ctx, project_dir, dry_run, resume, no_checklist):
    """Install or update a project.

    Uses checklist system by default (unless --no-checklist).
    """
    project_path = Path(project_dir).resolve()
    log_level = ctx.obj["log_level"]

    click.echo(f"🚀 {'Checking' if dry_run else 'Installing/Updating'} {project_path}")

    # Load manifest
    manifest_manager = ManifestManager(project_path)
    manifest = manifest_manager.load()

    # Initialize logger
    logger = StructuredLogger(project_path)

    if no_checklist:
        # Old behavior: direct execution
        _run_direct(project_path, manifest, logger, dry_run)
    else:
        # New behavior: checklist-based execution
        _run_checklist(project_path, manifest, logger, dry_run, resume)


def _run_direct(
    project_path: Path,
    manifest: Manifest,
    logger: StructuredLogger,
    dry_run: bool,
) -> None:
    """Run installation without checklist (legacy behavior)."""
    # Detect mode
    version_manager = VersionManager(project_path, logger)
    mode = version_manager.detect_mode()

    click.echo(f"  Mode: {mode}")

    # Check for updates
    latest = version_manager.get_latest_github_version()
    current = version_manager.get_local_version()
    click.echo(f"  Current: {current}")
    click.echo(f"  Latest: {latest}")

    # Sync
    if not dry_run:
        sync_manager = SyncManager(
            source_dir=project_path,
            dest_dir=project_path,
            manifest=manifest,
        )
        copied, deleted, zombies = sync_manager.sync()
        click.echo(f"  Synced: {copied} copied, {deleted} deleted, {len(zombies)} zombies")

    click.echo(f"✓ {'Dry-run complete' if dry_run else 'Installation complete'}")


def _run_checklist(
    project_path: Path,
    manifest: Manifest,
    logger: StructuredLogger,
    dry_run: bool,
    resume: Optional[str],
) -> None:
    """Run installation with checklist system."""
    engine = ChecklistEngine(
        project_dir=project_path,
        logger=logger,
    )

    # Load tasks from manifest
    engine.load_tasks_from_manifest(manifest)

    # Progress callback
    def on_progress(task: Task, step: Step):
        """Update CLI on progress."""
        progress = int(task.progress)
        status_icon = {
            TaskStatus.PENDING: "○",
            TaskStatus.RUNNING: "●",
            TaskStatus.COMPLETED: "✓",
            TaskStatus.FAILED: "✗",
            TaskStatus.SKIPPED: "−",
        }.get(step.status, "?")

        click.echo(
            f"  [{progress:3d}%] {task.name}/{step.name} {status_icon}"
        )

    # Run checklist
    success = engine.run(
        dry_run=dry_run,
        resume_from_checkpoint=resume,
        on_progress=on_progress,
    )

    if success:
        click.echo(f"\n✓ {'Dry-run complete' if dry_run else 'Installation complete'}")
    else:
        click.echo(f"\n✗ Installation failed (see logs)")
        click.exit(1)


@cli.command()
@click.argument("project_dir", type=click.Path())
@click.pass_context
def check(ctx, project_dir):
    """Check for updates.

    Compares local version with GitHub releases/latest.
    """
    project_path = Path(project_dir).resolve()
    logger = StructuredLogger(project_path)

    # Version manager
    version_manager = VersionManager(project_path, logger)

    # Get versions
    local = version_manager.get_local_version()
    git = version_manager.get_git_version()
    remote = version_manager.get_latest_github_version()

    # Display
    click.echo(f"📊 Version check for {project_path.name}")
    click.echo(f"\n  Local:  {local}")
    click.echo(f"  Git:    {git}")
    click.echo(f"  Remote: {remote}")

    # Check for update
    status = version_manager.check_for_update()
    click.echo(f"\n  Status: {status}")

    if status == VersionManager.UpdateStatus.OUTDATED:
        click.echo(f"\n⚠️  Update available: {local} → {remote}")
        click.echo(f"  Run: bash {project_path}/install.sh")
    elif status == VersionManager.UpdateStatus.UP_TO_DATE:
        click.echo(f"\n✓ Already at latest version")
    else:
        click.echo(f"\n⚠️  Cannot determine update status")


@cli.command()
@click.argument("project_dir", type=click.Path())
@click.pass_context
def version(ctx, project_dir):
    """Print version information."""
    project_path = Path(project_dir).resolve()
    logger = StructuredLogger(project_path)

    version_manager = VersionManager(project_path, logger)

    click.echo(f"Version information for {project_path.name}")
    click.echo(f"\n  Local:    {version_manager.get_local_version()}")
    click.echo(f"  Git:      {version_manager.get_git_version()}")
    click.echo(f"  Remote:   {version_manager.get_latest_github_version()}")


@cli.group()
def checklist():
    """Checklist management commands."""
    pass


@checklist.command("list")
@click.argument("project_dir", type=click.Path())
@click.pass_context
def checklist_list(ctx, project_dir):
    """List all checklists (in-progress and completed)."""
    project_path = Path(project_dir).resolve()
    logger = StructuredLogger(project_path)
    engine = ChecklistEngine(project_path, logger)

    checklists = engine.get_checklists()

    if not checklists:
        click.echo("No checklists found")
        return

    click.echo(f"📋 Checklists for {project_path.name}")
    for checklist in checklists:
        click.echo(f"\n  ID:      {checklist['checklist_id']}")
        click.echo(f"  Time:    {checklist['timestamp']}")
        click.echo(f"  Task:    {checklist['task_name']}")
        click.echo(f"  Step:    {checklist['step_index']}")
        click.echo(f"  Done:    {', '.join(checklist['completed_tasks'])}")


@checklist.command("run")
@click.argument("project_dir", type=click.Path())
@click.option("--dry-run", is_flag=True, help="Don't make changes")
@click.option("--verbose", is_flag=True, help="Show detailed output")
@click.pass_context
def checklist_run(ctx, project_dir, dry_run, verbose):
    """Run checklist for project."""
    project_path = Path(project_dir).resolve()
    logger = StructuredLogger(project_path)

    engine = ChecklistEngine(project_path, logger)

    # Load manifest
    manifest_manager = ManifestManager(project_path)
    manifest = manifest_manager.load()

    # Load tasks
    engine.load_tasks_from_manifest(manifest)

    # Progress callback
    def on_progress(task: Task, step: Step):
        if verbose:
            click.echo(
                f"  [{int(task.progress):3d}%] {task.name}/{step.name}"
            )

    success = engine.run(
        dry_run=dry_run,
        on_progress=on_progress,
    )

    if success:
        click.echo("✓ Checklist completed")
    else:
        click.echo("✗ Checklist failed")
        click.exit(1)


@checklist.command("resume")
@click.argument("project_dir", type=click.Path())
@click.argument("checklist_id")
@click.option("--dry-run", is_flag=True, help="Don't make changes")
@click.pass_context
def checklist_resume(ctx, project_dir, checklist_id, dry_run):
    """Resume checklist from checkpoint."""
    project_path = Path(project_dir).resolve()
    logger = StructuredLogger(project_path)

    engine = ChecklistEngine(project_path, logger)

    click.echo(f"🔄 Resuming checklist {checklist_id}")

    success = engine.resume(checklist_id)

    if success:
        click.echo("✓ Checklist resumed and completed")
    else:
        click.echo("✗ Checklist failed to resume")
        click.exit(1)


@cli.command()
@click.argument("project_dir", type=click.Path())
@click.option("--checklist-id", help="Filter by checklist ID")
@click.option("--output", type=click.Path(), help="Export logs to file")
@click.option("--format", type=click.Choice(["json", "csv"]), default="json", help="Export format")
@click.pass_context
def logs(ctx, project_dir, checklist_id, output, format):
    """View or export structured logs."""
    project_path = Path(project_dir).resolve()
    logger = StructuredLogger(project_path)

    logs = logger.get_logs(checklist_id=checklist_id)

    if output:
        # Export to file
        if checklist_id:
            filepath = logger.export_audit_trail(checklist_id, output_format=format)
        else:
            # Export all logs
            filepath = Path(output)
            with open(filepath, "w") as f:
                json.dump([log.to_dict() for log in logs], f, indent=2)

        click.echo(f"✓ Logs exported to {filepath}")
    else:
        # Display to console
        if not logs:
            click.echo("No logs found")
            return

        click.echo(f"📜 Logs ({len(logs)} entries)")
        for log in logs:
            level_icon = {
                "DEBUG": "🔍",
                "INFO": "ℹ️",
                "WARNING": "⚠️",
                "ERROR": "❌",
                "CRITICAL": "🚨",
            }.get(log.level, "•")

            click.echo(
                f"  {log.timestamp} [{level_icon}] {log.type.value}: {log.message}"
            )


@cli.command()
@click.option("--host", default="127.0.0.1", help="Host to bind to")
@click.option("--port", default=8000, type=int, help="Port to bind to")
@click.option("--reload", is_flag=True, help="Enable auto-reload")
@click.pass_context
def serve(ctx, host, port, reload):
    """Start REST API server."""
    click.echo(f"🌐 Starting REST API server on {host}:{port}")

    try:
        import uvicorn
        from .api import app

        uvicorn.run(app, host=host, port=port, reload=reload)
    except ImportError:
        click.echo("❌ FastAPI and/or uvicorn not installed")
        click.echo("   Install with: pip install fastapi uvicorn")
        click.exit(1)


if __name__ == "__main__":
    cli()
